# Generated by Django 3.2.12 on 2022-06-07 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_videodetail_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='pub_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
