# Generated by Django 3.2.12 on 2022-06-08 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_recorddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddays',
            name='last_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
