# Generated by Django 3.2.12 on 2022-06-08 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_recorddays_last_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddays',
            name='last_day',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 22, 25, 46, 923621)),
        ),
    ]
