# Generated by Django 3.2.12 on 2022-06-10 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_alter_recorddays_last_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='pub_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
