# Generated by Django 3.2.12 on 2022-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_videodetail_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
