# Generated by Django 3.2.12 on 2022-06-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0011_videodetail_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetail',
            name='duration',
        ),
        migrations.AddField(
            model_name='recorddays',
            name='max_continue_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecordAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game', models.PositiveIntegerField(default=0)),
                ('average_accuracy', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
