# Generated by Django 3.2.12 on 2022-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20220612_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetail',
            name='duration_h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videodetail',
            name='duration_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videodetail',
            name='duration_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recordaccuracy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recorddays',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videodetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
